spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 # Sentinel控制台地址
        port: 8719 # 本地启动的http服务端口，用于与Sentinel控制台通信
      eager: true # 是否立即加载Sentinel控制台
      filter:
        enabled: false # 关闭Sentinel的默认过滤器，我们将使用注解方式
server:
  port: 3389
